<?php

$localization = [
    'add company' => 'add company',
    'company' => 'company',
    'companies' => 'companies',
    'company name' => 'company name',
    'balance' => 'balance',
    'tier' => 'tier',
    'country' => 'country',
    'actions' => 'actions',
    'edit' => 'edit',
    'delete' => 'delete',
    'archive' => 'archive',
    'finance' => 'finance',
    'subscriptions' => 'subscriptions',
    'invoices' => 'invoices',
    'payments' => 'payments',
    'credits' => 'credits',
    'administration' => 'administration',
    'administrator' => 'administrator',
    'users' => 'users',
    'API keys' => 'cAPI keys',
    'settings' => 'settings',
    'logout' => 'logout',
    'general' => 'general',
    'financial' => 'finance',
    'account types' => 'account types',
    'templates' => 'templates',
    'subscription templates' => 'subscription templates',
    'maintenance' => 'maintenance',
    'mail queue' => 'mail queue',
    'audit logs' => 'audit logs',
    'backup' => 'backup',
    'debug' => 'debug',
    'localization' => 'localization',
    'security' => 'security',
    'email' => 'email',
    'webhooks' => 'webhooks',
    'taxes' => 'taxes',
    'profile' => 'profile',
    'logout' => 'logout',
    'monthly' => 'monthly',
];


