<?php 

$localization = [
    'add company' => 'entrada nueva empresa',
    'company' => 'empresa',
    'companies' => 'empresas',
    'company name' => 'nombre',
    'balance' => 'saldo de cuenta',
    'tier' => 'nivel',
    'country' => 'país',
    'actions' => 'acciones',
    'edit' => 'editar',
    'delete' => 'borrar',
    'archive' => 'archivar',
    'finance' => 'finanzas',
    'subscriptions' => 'suscripciones',
    'invoices' => 'facturas',
    'payments' => 'pagos',
    'credits' => 'créditos',
    'administration' => 'administración',
    'administrator' => 'administrador',
    'users' => 'usuarios',
    'API keys' => 'claves para API',
    'settings' => 'ajustes',
    'logout' => 'cerrar sesión',
    'general' => 'general',
    'financial' => 'financiero',
    'account types' => 'tipos de cuenta',
    'templates' => 'plantillas',
    'subscription templates' => 'plantillas de suscripción',
    'maintenance' => 'mantenimiento',
    'mail queue' => 'cola de correo',
    'audit logs' => 'registros de auditoría',
    'backup' => 'copia de seguridad',
    'debug' => 'depurar',
    'localization' => 'localización',
    'security' => 'seguridad',
    'email' => 'correo electrónico',
    'webhooks' => 'webhooks',
    'taxes' => 'impuestos',
    'profile' => 'perfil',
    'logout' => 'cerrar sesión',
    'monthly' => 'mensual',

];